nymea/nymea-zigbee

- libnymea-zigbee/zcl/general/zigbeeclusterlevelcontrol.cpp
- libnymea-zigbee/zcl/general/zigbeeclusterlevelcontrol.h
- libnymea-zigbee/zcl/general/zigbeeclusteronoff.cpp
- libnymea-zigbee/zcl/general/zigbeeclusteronoff.h
- libnymea-zigbee/zcl/general/zigbeeclusterscenes.cpp
- libnymea-zigbee/zcl/general/zigbeeclusterscenes.h
This alignes the OnOff cluster with the LevelControl cluster in terms
of signal behavior: Previously, the OnOff cluster would fire a generic
commandSent() signal for some commands and specific signals for others.
Effectively forcing the user to connect multiple signals even if only
the command would be of interest.
The LevelControl cluster instead always fired a generic commandSent()
signal and *additionally* more specific signals for parsed parameters.
This changes the OnOff cluster to be in line with the LevelCluster
as and making the API a bit simpler to use when parameters are not of
interest.
Also it completes the specific parsing for all 3 clusters.
> More work on OnOff, LevelControl and ScenesCluster

- debian/source/options
30MB -> 1.5MB and much faster builds
> Exclude docs and firmware binaries from dpkg source package

- debian/libnymea-zigbee-dev.install.in
- debian/libnymea-zigbee1.install.in
- libnymea-zigbee/libnymea-zigbee.pro
This is not needed (libraries already have version numers in their names) and quite uncommon.
> Remove 1 from lib name

- libnymea-zigbee/zcl/closures/zigbeeclusterdoorlock.cpp
- libnymea-zigbee/zcl/closures/zigbeeclusterdoorlock.h
- libnymea-zigbee/zcl/general/zigbeeclusteridentify.cpp
- libnymea-zigbee/zcl/general/zigbeeclusterlevelcontrol.cpp
- libnymea-zigbee/zcl/general/zigbeeclusterlevelcontrol.h
- libnymea-zigbee/zcl/general/zigbeeclusteronoff.cpp
- libnymea-zigbee/zcl/general/zigbeeclusteronoff.h
- libnymea-zigbee/zcl/general/zigbeeclusterscenes.cpp
- libnymea-zigbee/zcl/general/zigbeeclusterscenes.h
- libnymea-zigbee/zcl/hvac/zigbeeclusterthermostat.cpp
- libnymea-zigbee/zcl/lighting/zigbeeclustercolorcontrol.cpp
- libnymea-zigbee/zcl/lighting/zigbeeclustercolorcontrol.h
- libnymea-zigbee/zcl/manufacturerspecific/philips/zigbeeclustermanufacturerspecificphilips.cpp
- libnymea-zigbee/zcl/manufacturerspecific/philips/zigbeeclustermanufacturerspecificphilips.h
- libnymea-zigbee/zcl/ota/zigbeeclusterota.cpp
- libnymea-zigbee/zcl/security/zigbeeclusteriaszone.cpp
- libnymea-zigbee/zcl/security/zigbeeclusteriaszone.h
- libnymea-zigbee/zcl/zigbeecluster.cpp
- libnymea-zigbee/zcl/zigbeecluster.h
This patch separates the transactionSequenceNumber used for sending from the
one received. According to the specification, the transactionSequenceNumber is
not meant to equally increase on both ends, but instead really just be a "random"
number which allows to match a reply to a request. Syncing them on both ends
has the outcome to increase the likelyhood of collisions if a device sends
a notification at the same time we send a request and thus even may wrongly
interpret that incoming command as a reply to the request. In fact, ideally TSNs for
outgoing messages would stay away as far as possible from incoming ones.
The old code additionally had the problem that it would re-use the last received
TSN for outgoing requests, given it used a post-increment when reading …
> Refactor handling of TSNs in ZCL to allow the application using it.

- libnymea-zigbee/zdo/zigbeedeviceobject.cpp
- libnymea-zigbee/zdo/zigbeedeviceobjectreply.cpp
- libnymea-zigbee/zdo/zigbeedeviceobjectreply.h
I've been observing devices that won't reply to ZDO node descriptor requests,
at least not on the first attempt as well as out-of-spec devices which claim
to have an endpoint x but then won't reply on getting the endpoint descriptor.
I have a Lumi (lumi.sensor_switch.aq2) button here which allows to reproduce
both of those. It will never reply on the first attemt.
Anyhow, it happens that the ZDO, waiting on the data indication never finishes
because there does not seem to be a timeout connected to it and it fails initialisation.
Adding a timeout, the code retries and it seems to succeed on the second attempt.
> Timeout ZDO replies

- libnymea-zigbee/zcl/zigbeecluster.cpp
- libnymea-zigbee/zcl/zigbeeclusterreply.cpp
- libnymea-zigbee/zcl/zigbeeclusterreply.h
This is basically the same as #41 does with ZDO replies but for ZCL replies.
Working with a z-stack dongle and a Gewiss binary input device a lot of
timeouts happen during the device interview. While basic device interview
timeouts are caught by the ZDO timeouts, later interview steps like
cluster attribute reading run into the same issue with this device and
the interview process never finishes.
> Timeout ZCL replies

- libnymea-zigbee/zcl/zigbeecluster.cpp
- libnymea-zigbee/zdo/zigbeedeviceobject.cpp
Also don't use a QueuedConnection, as it's not guaranteed the
sender will still live on by the time slot is called.
> Explicitly stop the ZCL timeout timer

- libnymea-zigbee/backends/ti/zigbeebridgecontrollerti.cpp
This may happen on very rare occations after a nymea restart
if the controller is taking too long to initialize but still succeeds
in the end. Also increases the timeout for the procedure.
> Fix a crash if the controller takes too long to start

- libnymea-zigbee/zcl/smartenergy/zigbeeclustermetering.cpp
- libnymea-zigbee/zcl/smartenergy/zigbeeclustermetering.h
Main reasoning behind this is actually that Tuya devices seem
to send a CancelMessage command every other minute and are currently
spamming the log with unhandled ZCL indication warnings.
Instead of just silencing the warning (which is very useful most of the times)
I decided to complete the implementation of the metering cluster and
actually make it a handled ZCL indication which doesn't print warnings.
> Implement commands for metering cluster

- libnymea-zigbee/zdo/zigbeedeviceobject.cpp
- libnymea-zigbee/zdo/zigbeedeviceprofile.cpp
- libnymea-zigbee/zigbeenode.cpp
Parsing of NodeTypeEndDevice and NodeTypeRouter were swapped.
> Fix node type parsing

- libnymea-zigbee/backends/deconz/zigbeenetworkdeconz.cpp
- libnymea-zigbee/backends/nxp/zigbeenetworknxp.cpp
- libnymea-zigbee/backends/ti/zigbeebridgecontrollerti.cpp
The router broadcast address 0xFFFC is not a group addres, but a "regular" address. Setting the destinationAddressMode to GroupAddress caused the message to not be broadcastet and permit joining was only enabled on the coordinator.
This caused mainly the issue that joining a network would not work if the coordinator is out of reach.
In addition to that, there are quite a bit of end devices out there which behave badly in finding new parents and will stick to the node they joined in the first place forever, causing them to have bad signal if further away from the coordinator, even though there would be routers with much better LQI.
Additionally it fixes a permit joining issue in the TI backend which would prevent a call to setPermitJoining(0) to explicitly allow joining only on the …
> Fix permit joining in deconz backend

- libnymea-zigbee/backends/deconz/interface/zigbeeinterfacedeconzreply.cpp
- libnymea-zigbee/backends/deconz/zigbeebridgecontrollerdeconz.cpp
- libnymea-zigbee/backends/deconz/zigbeenetworkdeconz.cpp
- libnymea-zigbee/backends/deconz/zigbeenetworkdeconz.h
Currently, pretty much all zigbee calls done in setupThing() fail because the stack is still starting at startup.
Now that plugins are reworked to also better query the device states on a reconnect, this starts to show in failing calls. This pull request does two things:
a) It queues up calls in zigbeenetworkdeconz while the network is starting so they can be sent once the backend comes up. The TI backend already does this. I'm not sure what happens in the NXP backend, it queues up calls but also passes it down to the controller as long as it is not Offline (i.e. also when it's Starting). Depends on the firmware if those are queued up or failing/being discarded.
b) it also finishes the incomplete implementation of the apsFreeSlotsAvailable controller state in that it marks it as full when …
> Deconz: Fixes for command queuing

- libnymea-zigbee/backends/ti/zigbeebridgecontrollerti.cpp
The firmware provides parsed messages for those responses but we don't use them as nymea-zigbee parses this on its own.
> Silence a warning about unhandled callbacks

- libnymea-zigbee/backends/ti/zigbeebridgecontrollerti.cpp
- libnymea-zigbee/backends/ti/zigbeebridgecontrollerti.h
- libnymea-zigbee/backends/ti/zigbeenetworkti.cpp
This is required by some devices (at least Tradfri) in order to query us for images.
> Register the OTA server cluster on the TI backend

- libnymea-zigbee/zcl/zigbeecluster.cpp
- libnymea-zigbee/zcl/zigbeecluster.h
This is required to allow interacting with devices that use custom clusters and go beyond attribute reporting.
> Expose raw dataIndications and allow sending raw commands on ZigbeeCluster

- libnymea-zigbee/backends/deconz/zigbeebridgecontrollerdeconz.cpp
May happen if the queue runs full and controller requests time out
> Fix an occational crash in the deconz backend

- libnymea-zigbee/backends/ti/interface/zigbeeinterfaceti.cpp
- libnymea-zigbee/backends/ti/interface/zigbeeinterfacetireply.cpp
- libnymea-zigbee/backends/ti/interface/zigbeeinterfacetireply.h
- libnymea-zigbee/backends/ti/zigbeebridgecontrollerti.cpp
- libnymea-zigbee/backends/ti/zigbeebridgecontrollerti.h
- libnymea-zigbee/zcl/zigbeecluster.cpp
Fixes reconnecting the ZigBee controller after a reset during runtime
Resets may occur by unplugging the stick or calling a softReset() from
the software side.
Additionally resets the stick when 5 subsequent timeouts happen
as there are firmwares of the CC2652 available which tend to
crash occationally.
> TI: fix reconncting the controller at runtime 

- libnymea-zigbee/zigbeenetwork.cpp
- libnymea-zigbee/zigbeenetwork.h
This decouples the cyclic refreshing of reachability from the manual reading of the LQI tables:
Changes the reachable refresh to only poll once a minute, cycling devices that need polling. Also checking for reachable will now only read the LQI table. Also removes the coordinator node from the cyclic checks.
In case a manual refresh is triggered, both LQI and RTG tables will be read of all non-sleepy nodes, including the coordinator and without any delays in between polls.
> Rework the reachable refreshing and manual LQI/RTG fetching

- libnymea-zigbee/zcl/general/zigbeeclusterlevelcontrol.cpp
- libnymea-zigbee/zcl/general/zigbeeclusterlevelcontrol.h
- libnymea-zigbee/zcl/general/zigbeeclusteronoff.cpp
- libnymea-zigbee/zcl/general/zigbeeclusteronoff.h
- libnymea-zigbee/zcl/general/zigbeeclusterscenes.cpp
- libnymea-zigbee/zcl/general/zigbeeclusterscenes.h
- libnymea-zigbee/zcl/lighting/zigbeeclustercolorcontrol.cpp
- libnymea-zigbee/zcl/lighting/zigbeeclustercolorcontrol.h
Originally the intention was to add the commandReceived() signal to the ColorControl cluster but noticing differences in various clusters wrt commandSent() and commandReceived() namings of those signals.
Decided to commandReceived() as it feels more natural to use and also the Zigbee cluster spec uses that wording.
> Align command signal names in clusters

- libnymea-zigbee/zigbeenetwork.cpp
> Fix sleepy device being marked as reachable after a long time of being unreachable
